package mastermod

// Typical Mods charts 01-04 (Book 1 p.265).
func init() { //nolint:funlen,gochecknoinits,maintidx // declarative transcription
	register(
		// Chart 01, Typical Mods (Book 1 p.265): Flux, -5..+5.
		table(
			"Visibility",
			"Flux",
			-5,
			"0 Contact",
			"R Reading",
			"T Talking",
			"1 Vshort",
			"2 Short",
			"3 Medium",
			"4 Long",
			"5 Vlong",
			"6 Distant",
			"7 Vdistant",
			"8 Orbit",
		),
		table(
			"Environment",
			"Flux",
			-5,
			"Frigid",
			"Vcold",
			"Cold",
			"Chilly",
			"Cool",
			"Nice",
			"Warm",
			"VWarm",
			"Hot",
			"Vhot",
			"Scalding",
		),
		table(
			"Attitude",
			"Flux",
			-5,
			"Dismissive",
			"Unenthusiastic",
			"Unsupportive",
			"Unhelpful",
			"Indifferent",
			"Helpful",
			"Interested",
			"Individualist",
			"Supportive",
			"Attentive",
			"Enthusiastic",
		),
		table(
			"Conformity",
			"Flux",
			-5,
			"Sycophant",
			"Sheep",
			"Orthodox",
			"Collectivist",
			"Obedient",
			"Balanced",
			"Odd",
			"Rebellious",
			"Unorthodox",
			"Egotist",
			"Narcissist",
		),
		table(
			"Imagination",
			"Flux",
			-5,
			"Idiotic",
			"Foolish",
			"VDull",
			"Dull",
			"Pedestrian",
			"Ordinary",
			"Sharp",
			"Pretty",
			"VClever",
			"Creative",
			"Genius",
		),
		table(
			"Logic",
			"Flux",
			-5,
			"Indeterminate",
			"Fuzzy",
			"Meaningless",
			"False",
			"Probably False",
			"Logical",
			"Probably True",
			"True",
			"Self-Referential",
			"Unsolvable",
			"Paradoxical",
		),
		table(
			"Idea",
			"Flux",
			-5,
			"Derivative",
			"Boring",
			"Dull",
			"Uninspired",
			"Unoriginal",
			"Ordinary",
			"Novel",
			"Ingenious",
			"Innovative",
			"Imaginative",
			"Truly Inspired",
		),
		// Chart 02, Technology (Book 1 p.265): 1D, printed with roll 6 at the
		// top of each column; row for roll 1 is last.
		table("Technology VLow", "1D", 1, "3", "2", "1.6", "1.3", "1", "0"),
		table("Technology Low", "1D", 1, "7", "6", "5", "4", "3.6", "3.3"),
		table("Technology Med", "1D", 1, "10", "9", "8.5", "8", "7", "6"),
		table("Technology High", "1D", 1, "13", "12.5", "12", "11", "10", "9"),
		table("Technology VHigh", "1D", 1, "16", "15.5", "15", "14", "13", "12"),
		table("Technology XHigh", "1D", 1, "19", "18.5", "18", "17", "16", "15"),
		table("Technology UHigh", "1D", 1, "22", "21.5", "21", "20", "19", "18"),
		// The printed Fantastic header spans TWO sub-columns of values (Book 1
		// p.265): the roll-6 row ends "... 18 22 28" and the roll-1 row
		// "... 22 27 33" — nine numeric columns under eight headers. Both
		// sub-columns are registered, split as (Low) 22-27 and (High) 28-33.
		table("Technology Fantastic (Low)", "1D", 1, "27", "26", "25", "24", "23", "22"),
		table("Technology Fantastic (High)", "1D", 1, "33", "32", "31", "30", "29", "28"),
		table("Gravity", "1D", 1, "Normal", "Strong", "Vstrong", "Crippling", "Extreme", "Crushing"),
		table("Zero-G", "1D", 1, "Normal", "Abnormal", "Fluxing", "Disrupting", "Disorienting", "Chaotic"),
		table("Acceleration", "1D", 1, "Normal", "Strong", "Vstrong", "Crippling", "Extreme", "Crushing"),
		table(
			"Environmental Conditions",
			"1D",
			1,
			"Normal",
			"Bothersome",
			"Swirling",
			"Disrupting",
			"Disorienting",
			"Chaotic",
		),
		// Chart 03, Typical Mods (Book 1 p.265): a MODIFIED Flux running
		// -6..+6, 13 rows — wider than plain Flux's -5..+5. The extra rows
		// are printed in the book; do not trim them to 11.
		table(
			"Probability",
			"Flux",
			-6,
			"Impossible",
			"Highly Improbable",
			"Improbable",
			"Highly Unlikely",
			"Unlikely",
			"Not Likely",
			"Even Chance",
			"Possible",
			"Likely",
			"Probable",
			"Very Probable",
			"Almost Certain",
			"Certain",
		),
		table(
			"Severity",
			"Flux",
			-6,
			"None",
			"Trivial",
			"Negligible",
			"Very Minor",
			"Minor",
			"Mild",
			"Temporary",
			"Strong",
			"Major",
			"Severe",
			"Very Severe",
			"Devastating",
			"Total",
		),
		table(
			"Imminence",
			"Flux",
			-6,
			"Far Future",
			"Centuries",
			"Lifetime",
			"Generation",
			"Decades",
			"Years",
			"Months",
			"Weeks",
			"Days",
			"Hours",
			"Minutes",
			"Seconds",
			"Now",
		),
		table(
			"Order and Chaos",
			"Flux",
			-6,
			"Entropic Chaos",
			"Random",
			"Very Disordered",
			"Disordered",
			"Unstructured",
			"Tainted",
			"Truly Neutral",
			"Arranged",
			"Structured",
			"Ordered",
			"Very Ordered",
			"Systematic",
			"Primeval Order",
		),
		table(
			"Morality",
			"Flux",
			-6,
			"Purely Immoral",
			"Very Immoral",
			"Immoral",
			"Offensive",
			"Unpleasant",
			"Unkind",
			"Truly Neutral",
			"Nice",
			"Pleasant",
			"Affable",
			"Moral",
			"Very Moral",
			"Absolute Moral",
		),
		table(
			"Evidence and Proof",
			"Flux",
			-6,
			"Inconceivable",
			"Impossible",
			"A Mere Scintilla of Evidence",
			"An Air of Reality",
			"Reasonable Suspicion",
			"Probable Cause",
			"Preponderance",
			"Clear and Convincing",
			"Reasonable Doubt",
			"Beyond a Reasonable Doubt",
			"Shadow of a Doubt",
			"Beyond a Shadow of a Doubt",
			"Absolute",
		),
		// Chart 04, Comparatives and Brand Names (Book 1 p.265): Flux.
		table(
			"Comparatives",
			"Flux",
			-5,
			"Worst",
			"Atrocious",
			"Very Bad",
			"Worse",
			"Bad",
			"Average",
			"Good",
			"Better",
			"Very Good",
			"Excellent",
			"Best",
		),
		table(
			"Vilani Comparatives",
			"Flux",
			-5,
			"La Gasep",
			"Khiba",
			"Dulamas",
			"Ga Gasep",
			"Gasep",
			"Ligtar",
			"Kaar",
			"Biilem",
			"Ga Kaar",
			"Lamas",
			"La Kaar",
		),
		// NewSpeak's blank 0 cell is a real gap; the printed -5 cell is
		// "Worst*", whose asterisk is a footnote marker ("*Technically
		// Ungrammatical", Book 1 p.265), not row text.
		sparse(
			"NewSpeak",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 1, 2, 3, 4, 5},
			"Worst",
			"Double PlusUnGood",
			"PlusUnGood",
			"UnGood",
			"HalfUnGood",
			"HalfGood",
			"Good",
			"PlusGood",
			"DoublePlusGood",
			"Best",
		),
		table(
			"Imperial Brands",
			"Flux",
			-5,
			"Loamer",
			"Sloeph",
			"Cerfan",
			"Boron",
			"Neol Sibs",
			"Engolia",
			"Kosinar",
			"JPG",
			"Vereos",
			"Tyxagon",
			"Starling",
		),
		table(
			"Anglic Brands",
			"Flux",
			-5,
			"Glump",
			"NNA",
			"Peerless",
			"Consolidated",
			"Dorado",
			"Acme",
			"Ponii",
			"Golden",
			"Official TAS",
			"Iridium",
			"Corp 715",
		),
		table(
			"Vilani Brands",
			"Flux",
			-5,
			"Naa",
			"Kakna",
			"Seleni",
			"Lanuur",
			"Khush",
			"Ushum",
			"Ganun",
			"Shakashdir",
			"Sebiilem",
			"Agbar Urdim",
			"Karak",
		),
		table(
			"MegaCorp Brands",
			"Flux",
			-5,
			"General",
			"GsbAg",
			"Delgado",
			"Tukera",
			"SuSAG",
			"Makhid",
			"Zirunkarish",
			"Sharurshid",
			"Naasirka",
			"LSP",
			"Instellarms",
		),
	)
}
