package mastermod

func init() { //nolint:funlen,gochecknoinits,maintidx // declarative transcription
	register(
		table("Technology VLow", "1D", 1, "3", "2", "1.6", "1.3", "1", "0"),
		table("Technology Low", "1D", 1, "7", "6", "5", "4", "3.6", "3.3"),
		table("Technology Med", "1D", 1, "10", "9", "8.5", "8", "7", "6"),
		table("Technology High", "1D", 1, "13", "12.5", "12", "11", "10", "9"),
		table("Technology VHigh", "1D", 1, "16", "15.5", "15", "14", "13", "12"),
		table("Technology XHigh", "1D", 1, "19", "18.5", "18", "17", "16", "15"),
		table("Technology UHigh", "1D", 1, "22", "21.5", "21", "20", "19", "18"),
		table("Technology Fantastic", "1D", 1, "33", "32", "31", "30", "29", "28"),
		table("Gravity", "1D", 1, "Normal", "Strong", "Vstrong", "Crippling", "Extreme", "Crushing"),
		table("Zero-G", "1D", 1, "Normal", "Abnormal", "Fluxing", "Disrupting", "Disorienting", "Chaotic"),
		table("Acceleration", "1D", 1, "Normal", "Strong", "Vstrong", "Crippling", "Extreme", "Crushing"),
		table(
			"Environmental Conditions",
			"1D",
			1,
			"Normal",
			"Bothersome",
			"Swirling",
			"Disrupting",
			"Disorienting",
			"Chaotic",
		),
		table(
			"Probability",
			"Flux",
			-6,
			"Impossible",
			"Highly Improbable",
			"Improbable",
			"Highly Unlikely",
			"Unlikely",
			"Not Likely",
			"Even Chance",
			"Possible",
			"Likely",
			"Probable",
			"Very Probable",
			"Almost Certain",
			"Certain",
		),
		table(
			"Severity",
			"Flux",
			-6,
			"None",
			"Trivial",
			"Negligible",
			"Very Minor",
			"Minor",
			"Mild",
			"Temporary",
			"Strong",
			"Major",
			"Severe",
			"Very Severe",
			"Devastating",
			"Total",
		),
		table(
			"Imminence",
			"Flux",
			-6,
			"Far Future",
			"Centuries",
			"Lifetime",
			"Generation",
			"Decades",
			"Years",
			"Months",
			"Weeks",
			"Days",
			"Hours",
			"Minutes",
			"Seconds",
			"Now",
		),
		table(
			"Order and Chaos",
			"Flux",
			-6,
			"Entropic Chaos",
			"Random",
			"Very Disordered",
			"Disordered",
			"Unstructured",
			"Tainted",
			"Truly Neutral",
			"Arranged",
			"Structured",
			"Ordered",
			"Very Ordered",
			"Systematic",
			"Primeval Order",
		),
		table(
			"Morality",
			"Flux",
			-6,
			"Purely Immoral",
			"Very Immoral",
			"Immoral",
			"Offensive",
			"Unpleasant",
			"Unkind",
			"Truly Neutral",
			"Nice",
			"Pleasant",
			"Affable",
			"Moral",
			"Very Moral",
			"Absolute Moral",
		),
		table(
			"Evidence and Proof",
			"Flux",
			-6,
			"Inconceivable",
			"Impossible",
			"A Mere Scintilla of Evidence",
			"An Air of Reality",
			"Reasonable Suspicion",
			"Probable Cause",
			"Preponderance",
			"Clear and Convincing",
			"Reasonable Doubt",
			"Beyond a Reasonable Doubt",
			"Shadow of a Doubt",
			"Beyond a Shadow of a Doubt",
			"Absolute",
		),
		table(
			"Comparatives",
			"Flux",
			-5,
			"Worst",
			"Atrocious",
			"Very Bad",
			"Worse",
			"Bad",
			"Average",
			"Good",
			"Better",
			"Very Good",
			"Excellent",
			"Best",
		),
		table(
			"Vilani Comparatives",
			"Flux",
			-5,
			"La Gasep",
			"Khiba",
			"Dulamas",
			"Ga Gasep",
			"Gasep",
			"Ligtar",
			"Kaar",
			"Biilem",
			"Ga Kaar",
			"Lamas",
			"La Kaar",
		),
		sparse(
			"NewSpeak",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 1, 2, 3, 4, 5},
			"Worst*",
			"Double PlusUnGood",
			"PlusUnGood",
			"UnGood",
			"HalfUnGood",
			"HalfGood",
			"Good",
			"PlusGood",
			"DoublePlusGood",
			"Best",
		),
		table(
			"Imperial Brands",
			"Flux",
			-5,
			"Loamer",
			"Sloeph",
			"Cerfan",
			"Boron",
			"Neol Sibs",
			"Engolia",
			"Kosinar",
			"JPG",
			"Vereos",
			"Tyxagon",
			"Starling",
		),
		table(
			"Anglic Brands",
			"Flux",
			-5,
			"Glump",
			"NNA",
			"Peerless",
			"Consolidated",
			"Dorado",
			"Acme",
			"Ponii",
			"Golden",
			"Official TAS",
			"Iridium",
			"Corp 715",
		),
		table(
			"Vilani Brands",
			"Flux",
			-5,
			"Naa",
			"Kakna",
			"Seleni",
			"Lanuur",
			"Khush",
			"Ushum",
			"Ganun",
			"Shakashdir",
			"Sebiilem",
			"Agbar Urdim",
			"Karak",
		),
		table(
			"MegaCorp Brands",
			"Flux",
			-5,
			"General",
			"GsbAg",
			"Delgado",
			"Tukera",
			"SuSAG",
			"Makhid",
			"Zirunkarish",
			"Sharurshid",
			"Naasirka",
			"LSP",
			"Instellarms",
		),
		table("Number of Careers", "Flux", -6, "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"),
		table(
			"Careers",
			"Flux",
			-6,
			"Craftsman",
			"Scholar",
			"Entertainer",
			"Citizen",
			"Scout",
			"Merchant",
			"Spacer",
			"Soldier",
			"Agent",
			"Rogue",
			"Noble",
			"Marines",
			"Functionary",
		),
		table(
			"Nobility",
			"Flux",
			-6,
			"Commoner",
			"A Gentleman",
			"B Knight",
			"c Baronet",
			"C Baron",
			"D Marquis",
			"e Viscount",
			"E Count",
			"f Minor Duke",
			"F Duke",
			"G Archduke",
			"h Imperial Family",
			"H Emperor",
		),
		table(
			"Friends",
			"Flux",
			-6,
			"Nemesis",
			"Enemy",
			"Antagonist",
			"Adversary",
			"Rival",
			"Opponent",
			"Acquaintance",
			"Contact",
			"Friend",
			"Companion",
			"Fast Friend",
			"Best Friend",
			"Blood Sib",
		),
		table(
			"Humaniti",
			"Flux",
			-6,
			"Iltharan",
			"Thaggeshi",
			"Loeskalth",
			"Answerin",
			"Suerrat",
			"Cassildan",
			"Yiliean",
			"Luriani",
			"Darmine",
			"Geonee",
			"Azhanti",
			"Vlazdumecta",
			"Floriani",
		),
		table(
			"Sophonts1",
			"Flux",
			-6,
			"Shriekers",
			"Gurvin",
			"Ahetowa",
			"Ael Yael",
			"Llellewyloly",
			"Vegans",
			"Bwaps",
			"Virushi",
			"Eshar Ashah",
			"Mirani",
			"Jgd-Il-Jagd",
			"Lhshana",
			"Shi’awei",
		),
		table(
			"Sophonts2",
			"Flux",
			-6,
			"Crawni",
			"Obeyery",
			"Traltar",
			"Ebokin",
			"Ligtary",
			"Larianz",
			"Shriekers",
			"Tethmari",
			"Vanejenese",
			"Zurphani",
			"Takashi",
			"Otarri",
			"Ursty",
		),
		sparse(
			"Major Races",
			"Flux",
			[]int{-3, -2, -1, 0, 1, 2, 3, 5},
			"Hivers",
			"Aslan",
			"Zhodani",
			"Vilani",
			"Solomani",
			"Vargr",
			"K’kree",
			"Droyne",
		),
		table("World Size", "Flux", -5, "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F"),
		table(
			"Gravity G",
			"Flux",
			-5,
			"0.4",
			"0.5",
			"0.6",
			"0.7",
			"0.8",
			"1.0",
			"1.1",
			"1.2",
			"1.3",
			"1.5",
			"1.6",
			"1.8",
			"1.9",
		),
		table("Speed kph", "Flux", -5, "5", "10", "20", "30", "50", "100", "300", "500", "700", "1000", "2000"),
		sparse(
			"Walk",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3},
			"Creep",
			"Crawl",
			"Xslow",
			"Vslow Crawl",
			"Slow Stroll",
			"Standard Walk",
			"Cruise Trot",
			"Fast Run",
			"Vfast Sprint",
		),
		sparse(
			"Drive",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3},
			"Stuck",
			"Creeping",
			"Stop and Go",
			"Vslow",
			"Slow",
			"Drive",
			"Fast",
			"Vfast",
			"Racing",
		),
		sparse(
			"Highway",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4},
			"Stuck",
			"Creeping",
			"Jammed",
			"Slow",
			"Lagging",
			"Cruise",
			"Fast Lane",
			"Vfast Land",
			"Grid Control",
			"Speeding",
		),
		table(
			"Comms",
			"Flux",
			-5,
			"Jammed",
			"Equip Fault",
			"Equip Glitch",
			"Interference",
			"Static",
			"Good",
			"Very Good",
			"Excellent",
			"Clear",
			"Very Clear",
			"Crystal Clear",
		),
		table(
			"Weather",
			"Flux",
			-5,
			"Extremely Bad",
			"Very Bad",
			"Worse",
			"Bad",
			"Inconvenient",
			"Neutral",
			"Fortuitous",
			"Good",
			"Better",
			"Very Good",
			"Extremely Good",
		),
		sparse(
			"Sounds",
			"Flux",
			[]int{-2, -1, 0, 1, 2, 3, 4, 5, 6, 7},
			"Earbud",
			"Whisper",
			"Talking",
			"Lecture",
			"Shout",
			"Distress",
			"Many Distress",
			"Gunshot",
			"Thunder",
			"Explosion",
		),
	)
}
