package mastermod

// Typical Mods charts 17-21 (Book 1 p.269). Deliberately excluded from chart
// 21: the Imperiallines and Hortalez MegaCorporation rows, which are printed
// without 2x1D keys and so cannot be rolled.
func init() { //nolint:funlen,gochecknoinits // declarative transcription
	register(
		// Charts 17-20 (Book 1 p.269): 1D.
		table(
			"Sensor Responding",
			"1D",
			1,
			"Space Sensors",
			"World Sensors",
			"Specialized Sensors",
			"Jammers",
			"Crew Strange Feeling",
			"Sensor Failure",
		),
		table(
			"Space Sensors",
			"1D",
			1,
			"Strange Gravity Wave",
			"Unusual Magnetic Pulse",
			"Intense Neutrino Source",
			"Scanner Static",
			"Coded Signal",
			"Distress Call",
		),
		table(
			"World Sensors",
			"1D",
			1,
			"Signs of Mining Activity",
			"Subsurface Anomalies",
			"Life Detector Readings",
			"Mass Sensor Readings",
			"Volcanic Activity",
			"Seismic Activity",
		),
		table(
			"Specialized Sensors",
			"1D",
			1,
			"High Radiation Readings",
			"Windborne Radioactives",
			"Life Detector Fault",
			"Mass Sensor Anomaly",
			"Densitometer Anomaly",
			"Strange Readings",
		),
		table(
			"Local Observation",
			"1D",
			1,
			"Strange Weather",
			"Unusual Climate",
			"Sudden Darkness",
			"Increase In Temperature",
			"Decrease In Temperature",
			"Eclipse",
		),
		table(
			"Local Anomaly",
			"1D",
			1,
			"Magnetic Readings",
			"Gravitic Readings",
			"Seismic Readings",
			"Radio Wave Static",
			"Corrosion",
			"Programming Faults",
		),
		table(
			"Strange Warnings",
			"1D",
			1,
			"Strange Sounds",
			"Strange Clickings",
			"Strange Hum",
			"Several Failure Alarms",
			"Vehicle Won’t Start",
			"Device Failure",
		),
		table(
			"Local Unrest",
			"1D",
			1,
			"Dying Vegetation",
			"Sudden Animal Movement",
			"Sudden Vegetation Growth",
			"Animal Deaths",
			"Animal Illnesses",
			"Animal Insanity",
		),
		table(
			"Starport Situations",
			"1D",
			1,
			"Local Labor Unrest",
			"Incompetent Management",
			"Corrupt Management",
			"Bureaucratic Delays",
			"Construction Delays",
			"Major Repairs Ongoing",
		),
		table(
			"Startown Situations",
			"1D",
			1,
			"Active Antipathy",
			"Passive Antipathy",
			"Local Celebrations",
			"Holiday Atmosphere",
			"Excess Crowding",
			"Extreme Overpricing",
		),
		table(
			"Stellar Anomalies",
			"1D",
			1,
			"Stellar Flare",
			"Stellar EMP",
			"Stellar Dimming",
			"Stellar Spectral Changes",
			"Stellar Brightness Changes",
			"Stellar Gravity Waves",
		),
		table(
			"Minor Planets",
			"1D",
			1,
			"Radiation World Emergency",
			"BigWorld Catastrophe",
			"Reports of Shipwreck",
			"Noble Estate",
			"Remote Colony Distress Call",
			"Mercenary Camp",
		),
		table(
			"Outer System",
			"1D",
			1,
			"Gas Giant Fuel Contaminants",
			"Gas Giant Ring Disaster",
			"BigWorld Base Collapse",
			"StormWorld Disaster",
			"Gas Giant Sensor Readings",
			"Unexplained Distress Signals",
		),
		table(
			"Remote System",
			"1D",
			1,
			"Abandoned Orbital Fort",
			"Haunted Orbital Habitat",
			"Erratic Comets",
			"Out Of System Planetoid",
			"Old Mining Base",
			"Derelict Ship",
		),
		table(
			"Historical Ruins",
			"1D",
			1,
			"First Empire Base",
			"Second Empire Base",
			"Scientific Outpost",
			"Noble Estate",
			"Non-Human City",
			"Underground City",
		),
		table(
			"Reported Fault",
			"1D",
			1,
			"Interstellar Drive",
			"Interplanetary Drive",
			"Power System",
			"Life Support",
			"Cargo Hold",
			"Sensor System",
		),
		// Chart 21 (Book 1 p.269): MegaCorporations and QREBS are keyed 2x1D
		// (two 1D rolls read as digits, 11..66); the book marks Makhid,
		// Sharurshid, and Naasirka "*Original Vilani MegaCorporation".
		sparse(
			"MegaCorporations",
			"2x1D",
			[]int{11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25, 26},
			"General",
			"GsbAg",
			"Delgado",
			"Tukera",
			"SuSAG",
			"Makhid",
			"Zirunkarish",
			"Sharurshid",
			"Naasirka",
			"LSP",
			"Instellarms",
			"Sternmetal",
		),
		sparse("QREBS", "2x1D", []int{11, 12, 14, 15, 16, 21, 22, 23, 24, 25, 26},
			"Q-2 S+2", "R+1 B-1", "Q-1 R+2 S-1", "E+2 B+1 S-1", "Q+1",
			"S+1", "B-1", "E+1", "R+1", "R+1", "B+1"),
		// Chart 21 continued (Book 1 p.269): Damage Severity is keyed Hits/2
		// and Diagnosis Severity is printed as NINE rows (1..9) under a "1D"
		// header — the 7..9 rows are in the book; do not trim to 6.
		table(
			"Damage Severity",
			"Hits/2",
			1,
			"Easy 1D",
			"Average 2D",
			"Difficult 3D",
			"Formidable 4D",
			"Staggering 5D",
			"Hopeless 6D",
			"Impossible 7D",
			"Beyond 8D",
			"Destroyed",
		),
		table(
			"Diagnosis Severity",
			"1D",
			1,
			"Easy 1D",
			"Average 2D",
			"Difficult 3D",
			"Formidable 4D",
			"Staggering 5D",
			"Hopeless 6D",
			"Impossible 7D",
			"Beyond 8D",
			"Destroyed",
		),
	)
}
