package mastermod

func init() { //nolint:funlen,gochecknoinits,maintidx // declarative transcription
	register(
		sparse(
			"Planetary",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4},
			"Oc",
			"Fl",
			"As",
			"De",
			"Ga",
			"<none>",
			"He",
			"Ic",
			"Wa",
			"Va",
		),
		sparse("Population", "Flux", []int{-4, -3, -2, -1, 0, 1, 2}, "Di", "Ba", "Lo", "Ni", "<none>", "Ph", "Hi"),
		sparse(
			"Economic",
			"Flux",
			[]int{-4, -3, -2, -1, 0, 1, 2, 3, 4},
			"Pr",
			"Na",
			"Pa",
			"Po",
			"<none>",
			"Ag",
			"Ri",
			"Pi",
			"In",
		),
		sparse(
			"Climate",
			"Flux",
			[]int{-4, -3, -2, -1, 0, 1, 2, 3},
			"Lk",
			"Fr",
			"Co",
			"Tu",
			"<none>",
			"Tr",
			"Ho",
			"Tz",
		),
		sparse("Secondary", "Flux", []int{-3, -2, -1, 0, 1, 2}, "Fa", "Mi", "Mr", "<none>", "Pe", "Re"),
		sparse("Political", "Flux", []int{-2, -1, 0, 1, 2}, "Cx", "Cs", "<none>", "Cp", "Cy"),
		sparse("Special", "Flux", []int{-3, -2, -1, 0, 1, 2, 3}, "Fo", "Da", "Pz", "<none>", "Sa", "Ab", "An"),
		table(
			"Terrain1",
			"Flux",
			-5,
			"Rural",
			"Cropland",
			"Wetland Wood",
			"Wetland",
			"Clear Wood",
			"Clear",
			"Rough",
			"Rough Wood",
			"Mountain",
			"Desert",
			"Chasm",
		),
		table(
			"Terrain2",
			"Flux",
			-5,
			"Exotic",
			"Twilight Zone",
			"Baked Lands",
			"Shore",
			"Islands",
			"Ocean",
			"River",
			"Lake",
			"Ice Cap",
			"Ice Field",
			"Frozen Lands",
		),
		table(
			"Emotion",
			"Flux",
			-5,
			"Distress",
			"Hate",
			"Fear",
			"Surprise",
			"Unease",
			"Blank",
			"Calm",
			"Surprise",
			"Courage",
			"Love",
			"Delight",
		),
		table(
			"Degree",
			"Flux",
			-5,
			"Utmost",
			"Extreme",
			"Major",
			"Significant",
			"Minor",
			"Trivial",
			"Minor",
			"Significant",
			"Major",
			"Extreme",
			"Utmost",
		),
		table(
			"Potential",
			"Flux",
			-5,
			"Terrible",
			"Extremely Bad",
			"Very Bad",
			"Bad",
			"Poor",
			"Ordinary",
			"Possible",
			"Good",
			"Very Good",
			"Extremely Good",
			"Wonderful",
		),
		table(
			"Fraction",
			"Flux",
			-5,
			"Almost None",
			"One-Quarter",
			"Three-Eighths",
			"One-Third",
			"Almost Half",
			"Half",
			"More Than Half",
			"Two-Thirds",
			"Five-Eighths",
			"Three-Quarters",
			"Almost All",
		),
		table(
			"Rewards",
			"Flux",
			-5,
			"Insulting",
			"Insensitive",
			"Inadequate",
			"Insufficient",
			"Short",
			"Adequate",
			"Significant",
			"Satisfying",
			"Generous",
			"Very Generous",
			"Incredible",
		),
		table(
			"Standard Time In Jump",
			"Flux",
			-5,
			"158 hours",
			"160 hours",
			"162 hours",
			"164 hours",
			"166 hours",
			"168 hours",
			"170 hours",
			"172 hours",
			"174 hours",
			"176 hours",
			"178 hours",
		),
		table(
			"Naval Time In Jump",
			"Flux",
			-5,
			"163 hours",
			"164 hours",
			"165 hours",
			"166 hours",
			"167 hours",
			"168 hours",
			"169 hours",
			"170 hours",
			"171 hours",
			"172 hours",
			"173 hours",
		),
		table(
			"Supply",
			"Flux",
			-6,
			"Everpresent",
			"Ubiquitous",
			"Abundant",
			"Very Common",
			"Quite Common",
			"Common",
			"Typical",
			"Uncommon",
			"Scarce",
			"Rare",
			"Quite Rare",
			"Truly Rare",
			"Unique",
		),
		table(
			"Demand",
			"Flux",
			-6,
			"None",
			"Very Low",
			"Quite Low",
			"Low",
			"Weak",
			"Less Ordinary",
			"Ordinary",
			"Good",
			"Strong",
			"High",
			"Quite High",
			"Very High",
			"Absolute",
		),
		table(
			"Uncertainty",
			"Flux",
			-6,
			"Impossible",
			"Almost No Chance",
			"Highly Unlikely",
			"Little Chance",
			"Probably Not",
			"Less Than Even",
			"About Even",
			"Better Than Even",
			"Probably",
			"Very Good Chance",
			"Highly Likely",
			"Almost Certain",
			"Certain",
		),
		table(
			"Beauty",
			"Flux",
			-6,
			"Loathsome",
			"Repulsive",
			"Ugly",
			"Vunattractive",
			"Unattractive",
			"Vplain",
			"Plain",
			"Cute",
			"Pretty",
			"Vpretty",
			"Beautiful",
			"Helenic",
			"Perfect",
		),
		sparse(
			"Truth",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5},
			"GAEWK *",
			"Unsettling",
			"Obviously False",
			"False",
			"Not Quite",
			"Ordinary",
			"Good Enough",
			"True",
			"Obviously True",
			"Epiphany",
			"Absolute Truth",
		),
		sparse(
			"Respect",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5},
			"Ignored",
			"Utter Contempt",
			"Contempt",
			"Distaste",
			"Tolerance",
			"Peer",
			"Acknowledgement",
			"Respect",
			"Admiration",
			"Absolute Respect",
			"Idolization",
		),
		table(
			"Sense Visibility",
			"Flux",
			-5,
			"Contact",
			"Reading",
			"Talking",
			"Vshort",
			"Short",
			"Medium",
			"Long",
			"Vlong",
			"Distant",
			"Vdistant",
			"Orbit",
		),
		table(
			"Light",
			"Flux",
			-5,
			"Dark",
			"Very Dim",
			"Dim",
			"Obscured",
			"Hazy",
			"Visible",
			"Bright",
			"VBright",
			"UBright",
			"Blinding",
			"Burning",
		),
		table(
			"Sound",
			"Flux",
			-5,
			"Silent",
			"Subliminal",
			"Faint",
			"Whisper",
			"Soft",
			"Talking",
			"Loud",
			"Shout",
			"Cacaphony",
			"Deafening",
			"Destructive",
		),
		table(
			"Aroma",
			"Flux",
			-5,
			"Absent",
			"Subliminal",
			"Pheromone",
			"Pseudomone",
			"Subtle",
			"Ordinary",
			"Fragrant",
			"Pungent",
			"Stinking",
			"Stifling",
			"Overwhelming",
		),
		table(
			"Sensation",
			"Flux",
			-5,
			"Numb",
			"Insensitive",
			"Normal",
			"Tingling",
			"Discomfort",
			"Itch",
			"Stinging",
			"Painful",
			"VPainful",
			"Unbearable",
			"Scalding",
		),
		table(
			"Touch",
			"Flux",
			-5,
			"Frigid",
			"VCold",
			"Cold",
			"Chilly",
			"Cool",
			"Normal",
			"Warm",
			"VWarm",
			"Hot",
			"VHot",
			"Scalding",
		),
		table(
			"Sense Emotion",
			"Flux",
			-5,
			"Distress",
			"Hate",
			"Fear",
			"Surprise",
			"Unease",
			"Blank",
			"Calm",
			"Surprise",
			"Courage",
			"Love",
			"Delight",
		),
		sparse(
			"Large Groups",
			"Flux",
			[]int{0, 1, 2, 3, 4, 5},
			"Individuals",
			"Many People",
			"Hundreds",
			"Thousands",
			"10,000",
			"100,000",
		),
		sparse("QREBS", "2x1D", []int{11, 12, 14, 15, 16, 21, 22, 23, 24, 25, 26},
			"Q-2 S+2", "R+1 B-1", "Q-1 R+2 S-1", "E+2 B+1 S-1", "Q+1",
			"S+1", "B-1", "E+1", "R+1", "R+1", "B+1"),
	)
}
