package mastermod

// Typical Mods charts 09-12 (Book 1 p.267).
func init() { //nolint:funlen,gochecknoinits,maintidx // declarative transcription
	register(
		// Chart 09, Themes (Book 1 p.267): 1D.
		// "Truthfullness" is sic — the book prints the double-l in both
		// copies of this table (Book 1 p.267 and Book 3 p.279). epic
		// deliberately normalizes it; mastermod preserves the print.
		table("Theme1", "1D", 1, "Justice", "Happiness", "Kindness", "Honesty", "Truthfullness", "Cleanliness"),
		table("Theme2", "1D", 1, "Loyalty", "Cheerful", "Trustworthy", "Admiration", "Friendly", "Novelty"),
		table("Theme3", "1D", 1, "Awe", "Human Frailty", "Brave", "Bizarre", "Thrifty", "Profitable"),
		table("Theme4", "1D", 1, "Danger", "Paranoia", "Pursuit", "Revenge", "Humiliation", "Improbable"),
		table("Theme5", "1D", 1, "Laziness", "Heroism", "Escape", "Deception", "Conformity", "Extremes"),
		table("Theme6", "1D", 1, "Betrayal", "Disappointing", "Unreliable", "Stupidity", "Confusion", "Chaos"),
		// Chart 10, remarks/trade codes (Book 1 p.267): Flux. The "<none>"
		// rows are book-literal text — "Treat blank entries as <none>."
		sparse(
			"Planetary",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4},
			"Oc",
			"Fl",
			"As",
			"De",
			"Ga",
			"<none>",
			"He",
			"Ic",
			"Wa",
			"Va",
		),
		sparse("Population", "Flux", []int{-4, -3, -2, -1, 0, 1, 2}, "Di", "Ba", "Lo", "Ni", "<none>", "Ph", "Hi"),
		sparse(
			"Economic",
			"Flux",
			[]int{-4, -3, -2, -1, 0, 1, 2, 3, 4},
			"Pr",
			"Na",
			"Pa",
			"Po",
			"<none>",
			"Ag",
			"Ri",
			"Pi",
			"In",
		),
		sparse(
			"Climate",
			"Flux",
			[]int{-4, -3, -2, -1, 0, 1, 2, 3},
			"Lk",
			"Fr",
			"Co",
			"Tu",
			"<none>",
			"Tr",
			"Ho",
			"Tz",
		),
		sparse("Secondary", "Flux", []int{-3, -2, -1, 0, 1, 2}, "Fa", "Mi", "Mr", "<none>", "Pe", "Re"),
		sparse("Political", "Flux", []int{-2, -1, 0, 1, 2}, "Cx", "Cs", "<none>", "Cp", "Cy"),
		sparse("Special", "Flux", []int{-3, -2, -1, 0, 1, 2, 3}, "Fo", "Da", "Pz", "<none>", "Sa", "Ab", "An"),
		table(
			"Terrain1",
			"Flux",
			-5,
			"Rural",
			"Cropland",
			"Wetland Wood",
			"Wetland",
			"Clear Wood",
			"Clear",
			"Rough",
			"Rough Wood",
			"Mountain",
			"Desert",
			"Chasm",
		),
		table(
			"Terrain2",
			"Flux",
			-5,
			"Exotic",
			"Twilight Zone",
			"Baked Lands",
			"Shore",
			"Islands",
			"Ocean",
			"River",
			"Lake",
			"Ice Cap",
			"Ice Field",
			"Frozen Lands",
		),
		// Chart 11 (Book 1 p.267): Flux.
		table(
			"Emotion",
			"Flux",
			-5,
			"Distress",
			"Hate",
			"Fear",
			"Surprise",
			"Unease",
			"Blank",
			"Calm",
			"Surprise",
			"Courage",
			"Love",
			"Delight",
		),
		table(
			"Degree",
			"Flux",
			-5,
			"Utmost",
			"Extreme",
			"Major",
			"Significant",
			"Minor",
			"Trivial",
			"Minor",
			"Significant",
			"Major",
			"Extreme",
			"Utmost",
		),
		table(
			"Potential",
			"Flux",
			-5,
			"Terrible",
			"Extremely Bad",
			"Very Bad",
			"Bad",
			"Poor",
			"Ordinary",
			"Possible",
			"Good",
			"Very Good",
			"Extremely Good",
			"Wonderful",
		),
		table(
			"Fraction",
			"Flux",
			-5,
			"Almost None",
			"One-Quarter",
			"Three-Eighths",
			"One-Third",
			"Almost Half",
			"Half",
			"More Than Half",
			"Two-Thirds",
			"Five-Eighths",
			"Three-Quarters",
			"Almost All",
		),
		table(
			"Rewards",
			"Flux",
			-5,
			"Insulting",
			"Insensitive",
			"Inadequate",
			"Insufficient",
			"Short",
			"Adequate",
			"Significant",
			"Satisfying",
			"Generous",
			"Very Generous",
			"Incredible",
		),
		table(
			"Standard Time In Jump",
			"Flux",
			-5,
			"158 hours",
			"160 hours",
			"162 hours",
			"164 hours",
			"166 hours",
			"168 hours",
			"170 hours",
			"172 hours",
			"174 hours",
			"176 hours",
			"178 hours",
		),
		table(
			"Naval Time In Jump",
			"Flux",
			-5,
			"163 hours",
			"164 hours",
			"165 hours",
			"166 hours",
			"167 hours",
			"168 hours",
			"169 hours",
			"170 hours",
			"171 hours",
			"172 hours",
			"173 hours",
		),
		// Chart 12 (Book 1 p.267): mixed widths — Supply, Demand,
		// Uncertainty, and Beauty run -6..+6 (13 rows); Truth and Respect run
		// -5..+5 (Truth's -6 cell is blank; its +6 cell holds a footnote).
		table(
			"Supply",
			"Flux",
			-6,
			"Everpresent",
			"Ubiquitous",
			"Abundant",
			"Very Common",
			"Quite Common",
			"Common",
			"Typical",
			"Uncommon",
			"Scarce",
			"Rare",
			"Quite Rare",
			"Truly Rare",
			"Unique",
		),
		table(
			"Demand",
			"Flux",
			-6,
			"None",
			"Very Low",
			"Quite Low",
			"Low",
			"Weak",
			"Less Ordinary",
			"Ordinary",
			"Good",
			"Strong",
			"High",
			"Quite High",
			"Very High",
			"Absolute",
		),
		table(
			"Uncertainty",
			"Flux",
			-6,
			"Impossible",
			"Almost No Chance",
			"Highly Unlikely",
			"Little Chance",
			"Probably Not",
			"Less Than Even",
			"About Even",
			"Better Than Even",
			"Probably",
			"Very Good Chance",
			"Highly Likely",
			"Almost Certain",
			"Certain",
		),
		table(
			"Beauty",
			"Flux",
			-6,
			"Loathsome",
			"Repulsive",
			"Ugly",
			"Vunattractive",
			"Unattractive",
			"Vplain",
			"Plain",
			"Cute",
			"Pretty",
			"Vpretty",
			"Beautiful",
			"Helenic",
			"Perfect",
		),
		// The printed -5 cell is "GAEWK *"; the asterisk is a footnote marker
		// ("*Goes Against Everything We Know", Book 1 p.267), not row text.
		sparse(
			"Truth",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5},
			"GAEWK",
			"Unsettling",
			"Obviously False",
			"False",
			"Not Quite",
			"Ordinary",
			"Good Enough",
			"True",
			"Obviously True",
			"Epiphany",
			"Absolute Truth",
		),
		sparse(
			"Respect",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5},
			"Ignored",
			"Utter Contempt",
			"Contempt",
			"Distaste",
			"Tolerance",
			"Peer",
			"Acknowledgement",
			"Respect",
			"Admiration",
			"Absolute Respect",
			"Idolization",
		),
	)
}
