package mastermod

func init() { //nolint:funlen,gochecknoinits // declarative source data and registry validation
	register(
		table("Device Damage Location", "1D", 1, "Case", "Power", "Input", "Output", "Controls", "Processor"),
		table("Tool Damage Location", "1D", 1, "Case", "Power", "Adjuster", "Toolhead", "Grip", "Safety"),
		table("Weapon Damage Location", "1D", 1, "Frame", "Ammunition", "Sights", "Barrel", "Grip", "Mechanism"),
		table(
			"Heavy Weapon Damage Location",
			"2D",
			2,
			"Controls",
			"Mount",
			"Sights",
			"Shields",
			"Stocks",
			"Barrel",
			"Power",
			"Frame",
			"Ammunition",
			"Mechanism",
			"Computer",
		),
		table(
			"Vehicle or Armor Damage Location",
			"2D",
			2,
			"Controls",
			"Interior",
			"Visor",
			"Protections",
			"Life Support",
			"Locomotion",
			"Power",
			"Torso",
			"Manipulators",
			"Navigation",
			"Computer",
		),
		table(
			"Anatomical Damage Location",
			"2D",
			2,
			"Head",
			"Head",
			"Limb-Group-1",
			"Limb-Group-2",
			"Torso",
			"Torso",
			"Torso",
			"Limb-Grip-3",
			"Limb-Grip-4",
			"Graze",
			"Graze",
		),
		table(
			"Biological Damage Location",
			"2D",
			2,
			"Brain",
			"Senses",
			"Circulation",
			"Skeleton",
			"Respiration",
			"Skin",
			"Digestion",
			"Elimination",
			"Muscle",
			"Skin",
			"Skin",
		),
		table("Theme1", "1D", 1, "Justice", "Happiness", "Kindness", "Honesty", "Truthfullness", "Cleanliness"),
		table("Theme2", "1D", 1, "Loyalty", "Cheerful", "Trustworthy", "Admiration", "Friendly", "Novelty"),
		table("Theme3", "1D", 1, "Awe", "Human Frailty", "Brave", "Bizarre", "Thrifty", "Profitable"),
		table("Theme4", "1D", 1, "Danger", "Paranoia", "Pursuit", "Revenge", "Humiliation", "Improbable"),
		table("Theme5", "1D", 1, "Laziness", "Heroism", "Escape", "Deception", "Conformity", "Extremes"),
		table("Theme6", "1D", 1, "Betrayal", "Disappointing", "Unreliable", "Stupidity", "Confusion", "Chaos"),
		table(
			"Sensor Responding",
			"1D",
			1,
			"Space Sensors",
			"World Sensors",
			"Specialized Sensors",
			"Jammers",
			"Crew Strange Feeling",
			"Sensor Failure",
		),
		table(
			"Space Sensors",
			"1D",
			1,
			"Strange Gravity Wave",
			"Unusual Magnetic Pulse",
			"Intense Neutrino Source",
			"Scanner Static",
			"Coded Signal",
			"Distress Call",
		),
		table(
			"World Sensors",
			"1D",
			1,
			"Signs of Mining Activity",
			"Subsurface Anomalies",
			"Life Detector Readings",
			"Mass Sensor Readings",
			"Volcanic Activity",
			"Seismic Activity",
		),
		table(
			"Specialized Sensors",
			"1D",
			1,
			"High Radiation Readings",
			"Windborne Radioactives",
			"Life Detector Fault",
			"Mass Sensor Anomaly",
			"Densitometer Anomaly",
			"Strange Readings",
		),
		table(
			"Local Observation",
			"1D",
			1,
			"Strange Weather",
			"Unusual Climate",
			"Sudden Darkness",
			"Increase In Temperature",
			"Decrease In Temperature",
			"Eclipse",
		),
		table(
			"Local Anomaly",
			"1D",
			1,
			"Magnetic Readings",
			"Gravitic Readings",
			"Seismic Readings",
			"Radio Wave Static",
			"Corrosion",
			"Programming Faults",
		),
		table(
			"Strange Warnings",
			"1D",
			1,
			"Strange Sounds",
			"Strange Clickings",
			"Strange Hum",
			"Several Failure Alarms",
			"Vehicle Won’t Start",
			"Device Failure",
		),
		table(
			"Local Unrest",
			"1D",
			1,
			"Dying Vegetation",
			"Sudden Animal Movement",
			"Sudden Vegetation Growth",
			"Animal Deaths",
			"Animal Illnesses",
			"Animal Insanity",
		),
		table(
			"Starport Situations",
			"1D",
			1,
			"Local Labor Unrest",
			"Incompetent Management",
			"Corrupt Management",
			"Bureaucratic Delays",
			"Construction Delays",
			"Major Repairs Ongoing",
		),
		table(
			"Startown Situations",
			"1D",
			1,
			"Active Antipathy",
			"Passive Antipathy",
			"Local Celebrations",
			"Holiday Atmosphere",
			"Excess Crowding",
			"Extreme Overpricing",
		),
		table(
			"Stellar Anomalies",
			"1D",
			1,
			"Stellar Flare",
			"Stellar EMP",
			"Stellar Dimming",
			"Stellar Spectral Changes",
			"Stellar Brightness Changes",
			"Stellar Gravity Waves",
		),
		table(
			"Minor Planets",
			"1D",
			1,
			"Radiation World Emergency",
			"BigWorld Catastrophe",
			"Reports of Shipwreck",
			"Noble Estate",
			"Remote Colony Distress Call",
			"Mercenary Camp",
		),
		table(
			"Outer System",
			"1D",
			1,
			"Gas Giant Fuel Contaminants",
			"Gas Giant Ring Disaster",
			"BigWorld Base Collapse",
			"StormWorld Disaster",
			"Gas Giant Sensor Readings",
			"Unexplained Distress Signals",
		),
		table(
			"Remote System",
			"1D",
			1,
			"Abandoned Orbital Fort",
			"Haunted Orbital Habitat",
			"Erratic Comets",
			"Out Of System Planetoid",
			"Old Mining Base",
			"Derelict Ship",
		),
		table(
			"Historical Ruins",
			"1D",
			1,
			"First Empire Base",
			"Second Empire Base",
			"Scientific Outpost",
			"Noble Estate",
			"Non-Human City",
			"Underground City",
		),
		table(
			"Reported Fault",
			"1D",
			1,
			"Interstellar Drive",
			"Interplanetary Drive",
			"Power System",
			"Life Support",
			"Cargo Hold",
			"Sensor System",
		),
	)
}
