package mastermod

func init() { //nolint:funlen,gochecknoinits,maintidx // declarative transcription
	register(
		table(
			"Visibility",
			"Flux",
			-5,
			"0 Contact",
			"R Reading",
			"T Talking",
			"1 Vshort",
			"2 Short",
			"3 Medium",
			"4 Long",
			"5 Vlong",
			"6 Distant",
			"7 Vdistant",
			"8 Orbit",
		),
		table(
			"Environment",
			"Flux",
			-5,
			"Frigid",
			"Vcold",
			"Cold",
			"Chilly",
			"Cool",
			"Nice",
			"Warm",
			"VWarm",
			"Hot",
			"Vhot",
			"Scalding",
		),
		table(
			"Attitude",
			"Flux",
			-5,
			"Dismissive",
			"Unenthusiastic",
			"Unsupportive",
			"Unhelpful",
			"Indifferent",
			"Helpful",
			"Interested",
			"Individualist",
			"Supportive",
			"Attentive",
			"Enthusiastic",
		),
		table(
			"Conformity",
			"Flux",
			-5,
			"Sycophant",
			"Sheep",
			"Orthodox",
			"Collectivist",
			"Obedient",
			"Balanced",
			"Odd",
			"Rebellious",
			"Unorthodox",
			"Egotist",
			"Narcissist",
		),
		table(
			"Imagination",
			"Flux",
			-5,
			"Idiotic",
			"Foolish",
			"VDull",
			"Dull",
			"Pedestrian",
			"Ordinary",
			"Sharp",
			"Pretty",
			"VClever",
			"Creative",
			"Genius",
		),
		table(
			"Logic",
			"Flux",
			-5,
			"Indeterminate",
			"Fuzzy",
			"Meaningless",
			"False",
			"Probably False",
			"Logical",
			"Probably True",
			"True",
			"Self-Referential",
			"Unsolvable",
			"Paradoxical",
		),
		table(
			"Idea",
			"Flux",
			-5,
			"Derivative",
			"Boring",
			"Dull",
			"Uninspired",
			"Unoriginal",
			"Ordinary",
			"Novel",
			"Ingenious",
			"Innovative",
			"Imaginative",
			"Truly Inspired",
		),
		table("Crime", "1D", 1, "Gaffe", "Infraction", "Misdemeanor", "Felony", "High Crime", "Atrocity"),
		table("Property Crime", "1D", 1, "Misuse", "Vandalism", "Damage", "Theft", "Destruction", "Havoc"),
		table("Environmental Crime", "1D", 1, "Litter", "Waste", "Damage", "Pollution", "Ravage", "Ruin"),
		table("Sophont Crime", "1D", 1, "Offense", "Insult", "Assault", "Mayhem", "Killing", "Mass Killing"),
		table("Society Crime", "1D", 1, "Disharmony", "Rudeness", "Slack", "Dishonor", "Treason", "High Treason"),
		table("Justice", "1D", 1, "Mistake", "Inattention", "Inaction", "False Witness", "Injustice", "Tyranny"),
		table("Doctrine", "1D", 1, "Ignorance", "Question", "Heterodoxy", "Blasphemy", "Heresy", "Mass Deception"),
		table(
			"Groups1",
			"1D",
			1,
			"Individuals",
			"Groups",
			"Hundreds",
			"Thousands",
			"Ten Thousands",
			"Hundred Thousands",
			"Millions",
		),
		table(
			"Groups2",
			"1D",
			1,
			"Millions",
			"Hundred Thousands",
			"Ten Thousands",
			"Thousands",
			"Hundreds",
			"Groups",
			"Individuals",
		),
		table("Injury", "Bad Flux", -6, "Disastrous", "Vheavy", "Heavy", "Common", "Light", "Slight", "Scratch"),
		table(
			"Injury Severity",
			"Bad Flux",
			-6,
			"Near Total",
			"Intense",
			"Critical",
			"Serious",
			"Fair",
			"Good",
			"Scratch",
		),
		table("Diagnosis", "Bad Flux", -5, "Vobscure", "Obscure", "Difficult", "Hard", "Ordinary", "Easy"),
		sparse("Armor Mods", "Bad Flux", []int{-3, -2, -1, 0}, "Hvy Armor", "Armor", "Lt Armor", "Typical"),
		sparse("Evasion Mods", "Bad Flux", []int{-1, 0}, "Evade", "Typical"),
		table("Stability", "1D", 1, "Ordinary", "Easy", "Average", "Formidable", "Staggering", "Hopeless"),
		table("Typical BR", "1D", 1, "Ordinary", "Makhid", "Sharurshid", "Tukera", "SuSAG", "General"),
		table(
			"Typical DH",
			"1D",
			1,
			"Third Imperium",
			"Sword Worlds",
			"Zhodani Consulate",
			"Darrian Confederation",
			"Aslan Hierate",
			"2000 Worlds (K’kree)",
		),
		table("Xeno-Med", "1D", 1, "Ordinary", "Uncommon", "Strange", "Very Strange", "Obscure", "Illogical"),
		table(
			"Quality",
			"2D-2",
			-1,
			"Garbage",
			"Very Bad",
			"Bad",
			"Poor",
			"Lesser",
			"Below Average",
			"Average",
			"Better Than Some",
			"Better Than Many",
			"Very Good",
			"Better Than Most",
			"Excellent",
			"Superb",
			"Masterpiece",
		),
		table(
			"Quality Mod",
			"2D-2",
			-1,
			"-6",
			"-5",
			"-4",
			"-3",
			"-2",
			"-1",
			"0",
			"+1",
			"+2",
			"+3",
			"+4",
			"+5",
			"+6",
			"+7",
		),
		table(
			"Quality Period",
			"2D-2",
			-1,
			"Non-Functional",
			"Minutes",
			"Hours",
			"Days",
			"Weeks",
			"Months",
			"Half Year",
			"One Year",
			"Two Years",
			"Three Years",
			"Four Years",
			"Ten Years",
			"Twenty Years",
			"Centuries",
		),
		table(
			"Reliability",
			"Flux",
			-5,
			"Very Unreliable",
			"More Unreliable",
			"Unreliable",
			"Somewhat Unreliable",
			"Slightly Unreliable",
			"Reliability Neutral",
			"Better Than Some",
			"Better Than Many",
			"Reliable",
			"More Reliable",
			"Very Reliable",
		),
		table(
			"Ease Of Use",
			"Flux",
			-5,
			"Very Difficult To Use",
			"More Difficult To Use",
			"Hard To Use",
			"Somewhat Hard To Use",
			"Slightly Hard To Use",
			"Ease Of Use Neutral",
			"Better Than Some",
			"Better Than Many",
			"Easy To Use",
			"Easier To Use",
			"Very Easy To Use",
		),
		table(
			"Bulk/Burden",
			"Flux",
			-5,
			"Very Easy To Carry",
			"Easier To Carry",
			"Easy To Carry/Wear",
			"Better Than Many",
			"Better Than Some",
			"Burden Neutral",
			"Slightly Unergonomic",
			"Unwieldy",
			"Hard To Carry",
			"More Burdensom",
			"Very Burdensom",
		),
		table(
			"Safety",
			"Flux",
			-5,
			"Very Hazardous",
			"More Hazardous",
			"Hazardous",
			"Somewhat Hazardous",
			"Slightly Hazardous",
			"Safety Neutral",
			"Better Than Some",
			"Better Than Many",
			"Safe To Use",
			"Safer To Use",
			"Very Safe",
		),
		table(
			"Surprise",
			"Flux",
			-5,
			"Unaware",
			"Ambushed",
			"Very Surprised",
			"Surprised",
			"Unexpected",
			"Aware",
			"Predicted",
			"Anticipated",
			"Forewarned",
			"Prepared",
			"Very Prepared",
		),
		table(
			"Damage Severity",
			"Hits/2",
			1,
			"Easy 1D",
			"Average 2D",
			"Difficult 3D",
			"Formidable 4D",
			"Staggering 5D",
			"Hopeless 6D",
			"Impossible 7D",
			"Beyond 8D",
			"Destroyed",
		),
		table(
			"Diagnosis Severity",
			"1D",
			1,
			"Easy 1D",
			"Average 2D",
			"Difficult 3D",
			"Formidable 4D",
			"Staggering 5D",
			"Hopeless 6D",
			"Impossible 7D",
			"Beyond 8D",
			"Destroyed",
		),
		sparse(
			"MegaCorporations",
			"2x1D",
			[]int{11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25, 26},
			"General",
			"GsbAg",
			"Delgado",
			"Tukera",
			"SuSAG",
			"Makhid",
			"Zirunkarish",
			"Sharurshid",
			"Naasirka",
			"LSP",
			"Instellarms",
			"Sternmetal",
		),
	)
}
