package mastermod

// Typical Mods charts 05-08 (Book 1 p.266).
func init() { //nolint:funlen,gochecknoinits // declarative transcription
	register(
		// Chart 05 (Book 1 p.266): Groups1/Groups2 are printed as SEVEN rows
		// (1..7) under a "1D" header — the 7th row is in the book; do not
		// trim to 6.
		table(
			"Groups1",
			"1D",
			1,
			"Individuals",
			"Groups",
			"Hundreds",
			"Thousands",
			"Ten Thousands",
			"Hundred Thousands",
			"Millions",
		),
		table(
			"Groups2",
			"1D",
			1,
			"Millions",
			"Hundred Thousands",
			"Ten Thousands",
			"Thousands",
			"Hundreds",
			"Groups",
			"Individuals",
		),
		// Chart 05 continued (Book 1 p.266): Bad Flux columns; Injury and
		// Injury Severity run -6..0, Diagnosis -5..0, and the two Mods
		// columns have blank cells outside the keys transcribed here.
		table("Injury", "Bad Flux", -6, "Disastrous", "Vheavy", "Heavy", "Common", "Light", "Slight", "Scratch"),
		table(
			"Injury Severity",
			"Bad Flux",
			-6,
			"Near Total",
			"Intense",
			"Critical",
			"Serious",
			"Fair",
			"Good",
			"Scratch",
		),
		table("Diagnosis", "Bad Flux", -5, "Vobscure", "Obscure", "Difficult", "Hard", "Ordinary", "Easy"),
		sparse("Armor Mods", "Bad Flux", []int{-3, -2, -1, 0}, "Hvy Armor", "Armor", "Lt Armor", "Typical"),
		sparse("Evasion Mods", "Bad Flux", []int{-1, 0}, "Evade", "Typical"),
		// Chart 06, Crime versus (Book 1 p.266): 1D.
		table("Crime", "1D", 1, "Gaffe", "Infraction", "Misdemeanor", "Felony", "High Crime", "Atrocity"),
		table("Property Crime", "1D", 1, "Misuse", "Vandalism", "Damage", "Theft", "Destruction", "Havoc"),
		table("Environmental Crime", "1D", 1, "Litter", "Waste", "Damage", "Pollution", "Ravage", "Ruin"),
		table("Sophont Crime", "1D", 1, "Offense", "Insult", "Assault", "Mayhem", "Killing", "Mass Killing"),
		table("Society Crime", "1D", 1, "Disharmony", "Rudeness", "Slack", "Dishonor", "Treason", "High Treason"),
		table("Justice", "1D", 1, "Mistake", "Inattention", "Inaction", "False Witness", "Injustice", "Tyranny"),
		table("Doctrine", "1D", 1, "Ignorance", "Question", "Heterodoxy", "Blasphemy", "Heresy", "Mass Deception"),
		// Chart 07 (Book 1 p.266): another 13-row modified Flux, -6..+6.
		table("Number of Careers", "Flux", -6, "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"),
		table(
			"Careers",
			"Flux",
			-6,
			"Craftsman",
			"Scholar",
			"Entertainer",
			"Citizen",
			"Scout",
			"Merchant",
			"Spacer",
			"Soldier",
			"Agent",
			"Rogue",
			"Noble",
			"Marines",
			"Functionary",
		),
		table(
			"Nobility",
			"Flux",
			-6,
			"Commoner",
			"A Gentleman",
			"B Knight",
			"c Baronet",
			"C Baron",
			"D Marquis",
			"e Viscount",
			"E Count",
			"f Minor Duke",
			"F Duke",
			"G Archduke",
			"h Imperial Family",
			"H Emperor",
		),
		table(
			"Friends",
			"Flux",
			-6,
			"Nemesis",
			"Enemy",
			"Antagonist",
			"Adversary",
			"Rival",
			"Opponent",
			"Acquaintance",
			"Contact",
			"Friend",
			"Companion",
			"Fast Friend",
			"Best Friend",
			"Blood Sib",
		),
		table(
			"Humaniti",
			"Flux",
			-6,
			"Iltharan",
			"Thaggeshi",
			"Loeskalth",
			"Answerin",
			"Suerrat",
			"Cassildan",
			"Yiliean",
			"Luriani",
			"Darmine",
			"Geonee",
			"Azhanti",
			"Vlazdumecta",
			"Floriani",
		),
		table(
			"Sophonts1",
			"Flux",
			-6,
			"Shriekers",
			"Gurvin",
			"Ahetowa",
			"Ael Yael",
			"Llellewyloly",
			"Vegans",
			"Bwaps",
			"Virushi",
			"Eshar Ashah",
			"Mirani",
			"Jgd-Il-Jagd",
			"Lhshana",
			"Shi’awei",
		),
		table(
			"Sophonts2",
			"Flux",
			-6,
			"Crawni",
			"Obeyery",
			"Traltar",
			"Ebokin",
			"Ligtary",
			"Larianz",
			"Shriekers",
			"Tethmari",
			"Vanejenese",
			"Zurphani",
			"Takashi",
			"Otarri",
			"Ursty",
		),
		sparse(
			"Major Races",
			"Flux",
			[]int{-3, -2, -1, 0, 1, 2, 3, 5},
			"Hivers",
			"Aslan",
			"Zhodani",
			"Vilani",
			"Solomani",
			"Vargr",
			"K’kree",
			"Droyne",
		),
		// Chart 08, Gravity/Speed and Descriptive Speeds (Book 1 p.266): Flux.
		table("World Size", "Flux", -5, "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F"),
		table(
			"Gravity G",
			"Flux",
			-5,
			"0.4",
			"0.5",
			"0.6",
			"0.7",
			"0.8",
			"1.0",
			"1.1",
			"1.2",
			"1.3",
			"1.5",
			"1.6",
			"1.8",
			"1.9",
		),
		table("Speed kph", "Flux", -5, "5", "10", "20", "30", "50", "100", "300", "500", "700", "1000", "2000"),
		// Walk ("Human assumed", Book 1 p.266) runs -5..+5: the printed +4
		// and +5 rows are "Sonic" and "Ssonic" ("+4 C 1.5 1000 Sonic ...
		// Speeding" / "+5 D 1.6 2000 Ssonic").
		table(
			"Walk",
			"Flux",
			-5,
			"Creep",
			"Crawl",
			"Xslow",
			"Vslow Crawl",
			"Slow Stroll",
			"Standard Walk",
			"Cruise Trot",
			"Fast Run",
			"Vfast Sprint",
			"Sonic",
			"Ssonic",
		),
		sparse(
			"Drive",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3},
			"Stuck",
			"Creeping",
			"Stop and Go",
			"Vslow",
			"Slow",
			"Drive",
			"Fast",
			"Vfast",
			"Racing",
		),
		sparse(
			"Highway",
			"Flux",
			[]int{-5, -4, -3, -2, -1, 0, 1, 2, 3, 4},
			"Stuck",
			"Creeping",
			"Jammed",
			"Slow",
			"Lagging",
			"Cruise",
			"Fast Lane",
			"Vfast Land", // sic — the book prints "Land" under "Fast Lane"
			"Grid Control",
			"Speeding",
		),
		table(
			"Comms",
			"Flux",
			-5,
			"Jammed",
			"Equip Fault",
			"Equip Glitch",
			"Interference",
			"Static",
			"Good",
			"Very Good",
			"Excellent",
			"Clear",
			"Very Clear",
			"Crystal Clear",
		),
		table(
			"Weather",
			"Flux",
			-5,
			"Extremely Bad",
			"Very Bad",
			"Worse",
			"Bad",
			"Inconvenient",
			"Neutral",
			"Fortuitous",
			"Good",
			"Better",
			"Very Good",
			"Extremely Good",
		),
		// Sounds ("Sense: Hearing", Book 1 p.266) runs -2..+7.
		sparse(
			"Sounds",
			"Flux",
			[]int{-2, -1, 0, 1, 2, 3, 4, 5, 6, 7},
			"Earbud",
			"Whisper",
			"Talking",
			"Lecture",
			"Shout",
			"Distress",
			"Many Distress",
			"Gunshot",
			"Thunder",
			"Explosion",
		),
	)
}
