package mastermod

// Typical Mods charts 13-16 (Book 1 p.268). Deliberately excluded from chart
// 14: Barrier Height, Barrier Width, and Barrier Depth — their cells are blank
// in the printed appendix. Deliberately excluded from chart 15: Scene Mods —
// a formula ("Scene = Flux + Mods"), not a die table.
func init() { //nolint:funlen,gochecknoinits // declarative transcription
	register(
		// Chart 13, Mods for Senses (Book 1 p.268): Flux.
		table(
			"Sense Visibility",
			"Flux",
			-5,
			"Contact",
			"Reading",
			"Talking",
			"Vshort",
			"Short",
			"Medium",
			"Long",
			"Vlong",
			"Distant",
			"Vdistant",
			"Orbit",
		),
		table(
			"Light",
			"Flux",
			-5,
			"Dark",
			"Very Dim",
			"Dim",
			"Obscured",
			"Hazy",
			"Visible",
			"Bright",
			"VBright",
			"UBright",
			"Blinding",
			"Burning",
		),
		table(
			"Sound",
			"Flux",
			-5,
			"Silent",
			"Subliminal",
			"Faint",
			"Whisper",
			"Soft",
			"Talking",
			"Loud",
			"Shout",
			"Cacaphony",
			"Deafening",
			"Destructive",
		),
		table(
			"Aroma",
			"Flux",
			-5,
			"Absent",
			"Subliminal",
			"Pheromone",
			"Pseudomone",
			"Subtle",
			"Ordinary",
			"Fragrant",
			"Pungent",
			"Stinking",
			"Stifling",
			"Overwhelming",
		),
		table(
			"Sensation",
			"Flux",
			-5,
			"Numb",
			"Insensitive",
			"Normal",
			"Tingling",
			"Discomfort",
			"Itch",
			"Stinging",
			"Painful",
			"VPainful",
			"Unbearable",
			"Scalding",
		),
		table(
			"Touch",
			"Flux",
			-5,
			"Frigid",
			"VCold",
			"Cold",
			"Chilly",
			"Cool",
			"Normal",
			"Warm",
			"VWarm",
			"Hot",
			"VHot",
			"Scalding",
		),
		table(
			"Sense Emotion",
			"Flux",
			-5,
			"Distress",
			"Hate",
			"Fear",
			"Surprise",
			"Unease",
			"Blank",
			"Calm",
			"Surprise",
			"Courage",
			"Love",
			"Delight",
		),
		sparse(
			"Large Groups",
			"Flux",
			[]int{0, 1, 2, 3, 4, 5},
			"Individuals",
			"Many People",
			"Hundreds",
			"Thousands",
			"10,000",
			"100,000",
		),
		// Chart 14 (Book 1 p.268): 1D, printed with roll 6 at the top (the
		// margin also keys the rows as Bad Flux -5..0); Typical BR is
		// Bureaucratic Regulations, Typical DH is Diplomatic Handbook.
		table("Stability", "1D", 1, "Ordinary", "Easy", "Average", "Formidable", "Staggering", "Hopeless"),
		table("Typical BR", "1D", 1, "Ordinary", "Makhid", "Sharurshid", "Tukera", "SuSAG", "General"),
		table(
			"Typical DH",
			"1D",
			1,
			"Third Imperium",
			"Sword Worlds",
			"Zhodani Consulate",
			"Darrian Confederation",
			"Aslan Hierate",
			"2000 Worlds (K’kree)",
		),
		table("Xeno-Med", "1D", 1, "Ordinary", "Uncommon", "Strange", "Very Strange", "Obscure", "Illogical"),
		// Chart 15, QREBS Mods 1 (Book 1 p.268): 2D-2, rows -1(0)..12.
		table(
			"Quality",
			"2D-2",
			-1,
			"Garbage",
			"Very Bad",
			"Bad",
			"Poor",
			"Lesser",
			"Below Average",
			"Average",
			"Better Than Some",
			"Better Than Many",
			"Very Good",
			"Better Than Most",
			"Excellent",
			"Superb",
			"Masterpiece",
		),
		table(
			"Quality Mod",
			"2D-2",
			-1,
			"-6",
			"-5",
			"-4",
			"-3",
			"-2",
			"-1",
			"0",
			"+1",
			"+2",
			"+3",
			"+4",
			"+5",
			"+6",
			"+7",
		),
		table(
			"Quality Period",
			"2D-2",
			-1,
			"Non-Functional",
			"Minutes",
			"Hours",
			"Days",
			"Weeks",
			"Months",
			"Half Year",
			"One Year",
			"Two Years",
			"Three Years",
			"Four Years",
			"Ten Years",
			"Twenty Years",
			"Centuries",
		),
		// Chart 16, QREBS Mods 2 (Book 1 p.268): Flux.
		table(
			"Reliability",
			"Flux",
			-5,
			"Very Unreliable",
			"More Unreliable",
			"Unreliable",
			"Somewhat Unreliable",
			"Slightly Unreliable",
			"Reliability Neutral",
			"Better Than Some",
			"Better Than Many",
			"Reliable",
			"More Reliable",
			"Very Reliable",
		),
		table(
			"Ease Of Use",
			"Flux",
			-5,
			"Very Difficult To Use",
			"More Difficult To Use",
			"Hard To Use",
			"Somewhat Hard To Use",
			"Slightly Hard To Use",
			"Ease Of Use Neutral",
			"Better Than Some",
			"Better Than Many",
			"Easy To Use",
			"Easier To Use",
			"Very Easy To Use",
		),
		table(
			"Bulk/Burden",
			"Flux",
			-5,
			"Very Easy To Carry",
			"Easier To Carry",
			"Easy To Carry/Wear",
			"Better Than Many",
			"Better Than Some",
			"Burden Neutral",
			"Slightly Unergonomic",
			"Unwieldy",
			"Hard To Carry",
			"More Burdensom",
			"Very Burdensom",
		),
		table(
			"Safety",
			"Flux",
			-5,
			"Very Hazardous",
			"More Hazardous",
			"Hazardous",
			"Somewhat Hazardous",
			"Slightly Hazardous",
			"Safety Neutral",
			"Better Than Some",
			"Better Than Many",
			"Safe To Use",
			"Safer To Use",
			"Very Safe",
		),
		table(
			"Surprise",
			"Flux",
			-5,
			"Unaware",
			"Ambushed",
			"Very Surprised",
			"Surprised",
			"Unexpected",
			"Aware",
			"Predicted",
			"Anticipated",
			"Forewarned",
			"Prepared",
			"Very Prepared",
		),
	)
}
